[package]
name = "envbox-policy-service"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
envbox-core.workspace = true
envbox-launcher.workspace = true
envbox-storage.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
sha2 = "0.10"

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_System_Services", "Win32_Security_Authorization"] }
