[package]
name = "envbox-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "envbox-app"
path = "src/main.rs"

[dependencies]
envbox-core = { workspace = true }
envbox-storage = { workspace = true }
envbox-launcher = { workspace = true }
uuid = { workspace = true }
iced = { version = "0.13", features = ["tokio"] }
