[package]
name = "envbox-launcher"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
envbox-core = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }

[dev-dependencies]
envbox-core = { workspace = true }
uuid = { workspace = true }
