[package]
name = "envbox-launcher"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
envbox-core = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
sha2 = "0.10"

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_System_Diagnostics_ToolHelp", "Win32_Security_Authorization"] }

[dev-dependencies]
envbox-core = { workspace = true }
uuid = { workspace = true }
